<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Copyright>GD Seirya &amp; Mithras Seirya</Copyright>
    <Description>A cooperative multiplayer mod for Star Ocean: The Second Story R, built using BepInEx and Unity IL2CPP modding tools.</Description>
    <PackageReleaseNotes>Initial release of the mod.</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>G:\Documents\Unity Modding\SO2R Modding\SO2R Modding Station\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>G:\Documents\Unity Modding\SO2R Modding\SO2R Modding Station\BepInEx\interop\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Core">
      <HintPath>G:\Documents\Unity Modding\SO2R Modding\SO2R Modding Station\BepInEx\core\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>G:\Documents\Unity Modding\SO2R Modding\SO2R Modding Station\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>G:\Documents\Unity Modding\SO2R Modding\SO2R Modding Station\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>G:\Documents\Unity Modding\SO2R Modding\SO2R Modding Station\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>G:\Documents\Unity Modding\SO2R Modding\SO2R Modding Station\BepInEx\interop\Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>G:\Documents\Unity Modding\SO2R Modding\SO2R Modding Station\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>G:\Documents\Unity Modding\SO2R Modding\SO2R Modding Station\BepInEx\interop\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>G:\Documents\Unity Modding\SO2R Modding\SO2R Modding Station\BepInEx\interop\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>G:\Documents\Unity Modding\SO2R Modding\SO2R Modding Station\BepInEx\interop\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>G:\Documents\Unity Modding\SO2R Modding\SO2R Modding Station\BepInEx\interop\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>G:\Documents\Unity Modding\SO2R Modding\SO2R Modding Station\BepInEx\interop\UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
